package GenerateImmatureBuildingBlocks

import fenixTestCaseBuilderServerGrpcApi "github.com/jlambert68/FenixGrpcApi/FenixTestCaseBuilderServer/fenixTestCaseBuilderServerGrpcApi/go_grpc_api"

// Generate all Immature TestInstructionContainers for Sub Custody
func generateImmatureTestInstructionContainersMessagesSubCustody() (
	immatureTestInstructionContainers []*fenixTestCaseBuilderServerGrpcApi.ImmatureTestInstructionContainerMessage) {

	return immatureTestInstructionContainers
}
