package TestInstructions

import (
	"github.com/jlambert68/FenixTestInstructionsDataAdmin/SubCustody/TestInstructions/TestInstruction_GeneralSetupTearDown_TestCaseSetUp/version_1_0"
	__12 "github.com/jlambert68/FenixTestInstructionsDataAdmin/SubCustody/TestInstructions/TestInstruction_GeneralSetupTearDown_TestCaseTearDown/version_1_0"
)

func InitiateTestInstructionsFor_GeneralSeupTearDown() AllTestInstructions_SC_TestCaseSetUpStruct {

	var allTestInstructions_SC_TestCaseSetUp AllTestInstructions_SC_TestCaseSetUpStruct

	// Generate data for TestInstructionsMap within 'GeneralSeupTearDown'
	testInstruction_SC_TestCaseSetUp := version_1_0.Initate_TestInstruction_SC_TestCaseSetUp()
	testInstruction_SC_TestCaseTearDown := __12.Initate_TestInstruction_SC_TestCaseTearDown()

	// Append 'TestCaseSetUp' TestInstructionsMap into one structure
	allTestInstructions_SC_TestCaseSetUp.TestInstruction = append(
		allTestInstructions_SC_TestCaseSetUp.TestInstruction,
		testInstruction_SC_TestCaseSetUp.TestInstruction)
	allTestInstructions_SC_TestCaseSetUp.BasicTestInstructionInformation = append(
		allTestInstructions_SC_TestCaseSetUp.BasicTestInstructionInformation,
		testInstruction_SC_TestCaseSetUp.BasicTestInstructionInformation)
	allTestInstructions_SC_TestCaseSetUp.ImmatureTestInstructionInformation = append(
		allTestInstructions_SC_TestCaseSetUp.ImmatureTestInstructionInformation,
		testInstruction_SC_TestCaseSetUp.ImmatureTestInstructionInformation...)
	allTestInstructions_SC_TestCaseSetUp.TestInstructionAttribute = append(
		allTestInstructions_SC_TestCaseSetUp.TestInstructionAttribute,
		testInstruction_SC_TestCaseSetUp.TestInstructionAttribute...)
	allTestInstructions_SC_TestCaseSetUp.ImmatureElementModel = append(
		allTestInstructions_SC_TestCaseSetUp.ImmatureElementModel,
		testInstruction_SC_TestCaseSetUp.ImmatureElementModel...)
	allTestInstructions_SC_TestCaseSetUp.FangEngineClassesMethodsAttributes = append(
		allTestInstructions_SC_TestCaseSetUp.FangEngineClassesMethodsAttributes,
		testInstruction_SC_TestCaseSetUp.FangEngineClassesMethodsAttributes)

	// Append 'TestCaseSetUp' TestInstructionsMap into one structure
	allTestInstructions_SC_TestCaseSetUp.TestInstruction = append(
		allTestInstructions_SC_TestCaseSetUp.TestInstruction,
		testInstruction_SC_TestCaseTearDown.TestInstruction)
	allTestInstructions_SC_TestCaseSetUp.BasicTestInstructionInformation = append(
		allTestInstructions_SC_TestCaseSetUp.BasicTestInstructionInformation,
		testInstruction_SC_TestCaseTearDown.BasicTestInstructionInformation)
	allTestInstructions_SC_TestCaseSetUp.ImmatureTestInstructionInformation = append(
		allTestInstructions_SC_TestCaseSetUp.ImmatureTestInstructionInformation,
		testInstruction_SC_TestCaseTearDown.ImmatureTestInstructionInformation...)
	allTestInstructions_SC_TestCaseSetUp.TestInstructionAttribute = append(
		allTestInstructions_SC_TestCaseSetUp.TestInstructionAttribute,
		testInstruction_SC_TestCaseTearDown.TestInstructionAttribute...)
	allTestInstructions_SC_TestCaseSetUp.ImmatureElementModel = append(
		allTestInstructions_SC_TestCaseSetUp.ImmatureElementModel,
		testInstruction_SC_TestCaseTearDown.ImmatureElementModel...)
	allTestInstructions_SC_TestCaseSetUp.FangEngineClassesMethodsAttributes = append(
		allTestInstructions_SC_TestCaseSetUp.FangEngineClassesMethodsAttributes,
		testInstruction_SC_TestCaseTearDown.FangEngineClassesMethodsAttributes)

	return allTestInstructions_SC_TestCaseSetUp
}
